### ISSUE TITLE
NOT support BackendConfig ??

### ISSUE THREAD

**Issue by OrangePieiep** [hashicorp/terraform-provider-kubernetes#764]
Hi there,

Does k8s provider support BackendConfig ? If, Is there any alternative way?  

https://cloud.google.com/kubernetes-engine/docs/concepts/backendconfig
How to translate the following yaml to HCL ?

```yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: my-policy
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: my-iap-secret
```

**Comment by alexsomesan** [comment]
BackendConfig is Custom Resource type, as explained in the docs link you provided.
The Kubernetes provider currently does not provider support for CRDs to to technical limitations in the provider API. We are working in on experimental support for custom resources as a separate project, but efforts are still ongoing. We will update you when this becomes available.

**Comment by MPV** [comment]
Meanwhile, here are some options/workarounds on how you could do this: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/215#issuecomment-572686066

Myself, I'm using https://github.com/banzaicloud/terraform-provider-k8s

**Comment by aareet** [comment]
@OrangePieiep have you tested our new alpha provider https://github.com/hashicorp/terraform-provider-kubernetes-alpha for this issue?

**Comment by iBrandyJackson** [comment]
We suspect this issue is now resolved. We are closing this ticket. If you have found a problem that seems related to this change, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further. This helps our maintainers find and focus on the active issues. Thanks!

**Comment by yocontra** [comment]
Hi @iBrandyJackson - this issue is still not resolved, can you please reopen?

**Comment by iBrandyJackson** [comment]
Thank you @yocontra - we will add this to our next available triage slot to take a closer look against our assumptions.
